name: Production - Netlify

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        node-version: [10.21.0]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: yarn install
    - name: Building Project
      run: |
        yarn build
        yarn export
    - name: Deploy
      run: |
        yarn add netlify-cli
        yarn netlify deploy --dir=dist/ --site=${{secrets.NETLIFY_SITE_ID}} --prod
      env:
        CI: true
        NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_TOKEN}}
        NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
